### ISSUE TITLE
operator-cli update command fails for gui

### ISSUE THREAD

**Issue by phy-chain** [shardeum/shardeum-validator-cli#33]
When running the command `operator-cli update`, dry-run fails for gui with the following error (although `ls -la` shows the gui directory) :

```
----- STARTING GUI UPDATE PROCESS -----
Found a new version, starting update...
Running update dry run

Cloning into 'gui'...
fatal: Remote branch new-gui not found in upstream origin
update.sh: 30: cd: can't cd to gui

exec error: Error: Command failed: sh update.sh
Cloning into 'gui'...
fatal: Remote branch new-gui not found in upstream origin
update.sh: 30: cd: can't cd to gui

```

**Comment by kenny-io** [comment]
Hey @phy-chain I suspect that you're using the old installer script which is why it is trying to clone the `new-gui` branch of the Validator GUI which has since been deprecated.

This is the latest install script:

```
curl -O https://raw.githubusercontent.com/shardeum/validator-dashboard/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

If you found the old script anywhere in our docs, please share a link to it so we can update
